dist: xenial
language: node_js

node_js:
  - "node"
  - "8"
  
addons:
  apt:
    packages:
    - ffmpeg
    
before_install:
  - which ffmpeg
  - chmod +x ./aym.sh

script: ./aym.sh https://www.youtube.com/watch?v=6Olt-ZtV_CE
